settings:
  legacy:
    force: false
    interval: 0s
schema:
- name: /home/vagrant/go/src/github.com/fluidkeys/dashboard
  path: /home/vagrant/go/src/github.com/fluidkeys/dashboard
  commands:
    install:
      status: true
    run:
      status: true
  watcher:
    extensions:
    - go
    paths:
    - /
    ignored_paths:
    - .git
    - .realize
    - vendor
